import React from 'react';
import { PageWithIntro } from '@nwm/uifabric';
import { Text, Stack } from 'office-ui-fabric-react';
import TdpSearch from './TdpSearch';
import TdpLinks from './TdpLinks';

const tdpIndexHeader = {
  title: 'Technical Data Parameter Dictionary (TDP)',
  description:
    'The Technical Data Parameter Dictionary is a dictionary of standardized technical terms which is used to identify all project technical data.  These standardized terms, i.e., parameters and attributes, provide the common language needed for storing and retrieving the project technical data generated by or required for site characterization activities, socioeconomic and environmental assessments, design and development activities and performance assessment.',
};

export default function TdpIndex() {
  return (
    <PageWithIntro title={tdpIndexHeader.title}>
      <Text>{tdpIndexHeader.description}</Text>
      <Stack style={{ marginLeft: '55px' }}>
        <TdpLinks />
        <TdpSearch />
      </Stack>
    </PageWithIntro>
  );
}
